cloud:
  aws:
    credentials:
      access-key: AKIAXOAOFEDARKSTWDGK
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: withpetimg/test/
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB